[package]
name = "frontend"
version = "0.1.0"
authors = ["Jonas Lauschke"]
edition = "2021"

license = "AGPL-3.0"

[dependencies]
reqwest = { version = "^0.11", features = [
  "rustls",
  "rustls-tls",
] } # we use rustls because FUCK YOU OPENSSL FUCK YOU FUCK YOU LINKER ERROR
rkyv = "^0.7"
tokio = { version = "1", features = ["full"] }
einkaufsliste = { path = "../" }
bytes = "1"
zerocopy = "^0.6"
