[package]
name = "web_frontend"
version = "0.1.0"
authors = ["Jonas Lauschke"]
edition = "2021"

license = "AGPL-3.0"

[dependencies]
reqwest = { version = "0.11.10", default-features = false, features = [
  "rustls-tls",
  "brotli",
  "cookie_crate",
  "cookie_store",
] } # we use rustls because openssl doesn't do wasm
rkyv = { version = "0.7.38", features = ["archive_be"] }
einkaufsliste = { path = "../" }
bytes = "1.1.0"
zerocopy = "0.6.1"
futures = "0.3.21"
yew = "0.19.3"
web-sys = { version = "0.3.57", features = [
  "Element",
  "HtmlElement",
  "Node",
  "DomTokenList",
  "Window",
  "HtmlDivElement",
] }
log = "0.4.17"
console_log = { version = "0.2.0", features = ["color"] }
gloo-timers = { version = "0.2.4", features = ["futures"] }
yew-router = "0.16.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
