[package]
name = "frontend"
version = "0.1.0"
authors = ["Jonas Lauschke"]
edition = "2021"

license = "AGPL-3.0"

[dependencies]
reqwest = { version = "0.11.10", features = ["rustls"] }
rkyv = "0.7.38"
tokio = { version = "1.18.2", features = ["full"] }
einkaufsliste = {path = "../"}
bytes = "1.1.0"
zerocopy = "0.6.1"
