[package]
name = "einkaufsliste"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck = "0.6.9"
rkyv = { version = "0.7.39", features = [
  "bytecheck",
  "validation",
  "archive_be",
] }
zerocopy = "0.6.1"
einkaufsliste-codegen = { version = "*", path = "./codegen" }

actix-web = { version = "4", optional = true }
bytes = { version = "1", optional = true }
futures = { version = "0", optional = true }
async-trait = { version = "0.1.57", optional = true }
log = { version = "*", optional = true }

[features]
default = []
backend = ["actix-web", "bytes", "futures", "async-trait", "log"]

[workspace]
members = ["frontend", "backend", "codegen", "runner"]

[lib]
path = "lib/lib.rs"
