[package]
name = "einkaufsliste"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck = "0.6.8"
rkyv = { version = "0.7.38", features = [
  "bytecheck",
  "validation",
  "archive_be",
] }
zerocopy = "0.6.1"

[workspace]
members = ["frontend", "backend", "el_macro"]

[lib]
path = "lib/lib.rs"
