binop_separator = "Back"
color = "Always"
edition = "2021"
format_code_in_doc_comments = true
format_strings = true
max_width = 120
imports_granularity = "Module"
newline_style = "Unix"
group_imports = "StdExternalCrate"
tab_spaces = 2
unstable_features = true