[package]
name = "backend"
version = "0.1.0"
authors = ["Jonas Lauschke"]
edition = "2021"
license = "AGPL-3.0"

[dependencies]
actix-web = { version = "4.1.0", features = ["rustls", "secure-cookies"] }
bytecheck = "0.6.8"
bytes = "1.1.0"
env_logger = "0.9.0"
futures = "0.3.21"
log = "0.4.17"
rkyv = { version = "0.7.39", features = [
  "bytecheck",
  "validation",
  "archive_be",
] }
sled = "0.34.7"
tokio = "1.19.2"
zerocopy = "0.6.1"
einkaufsliste = { path = "../" }
rustls = "0.20.6"
rustls-pemfile = "1.0.0"
rand = { version = "0.8.5" }
blake3 = "1.3.1"
actix-session = { version = "0.6.2", features = ["cookie-session"] }
actix-identity = "0.4.0"
rand_xoshiro = "0.6.0"
actix-cors = "0.6.1"
