[package]
name = "backend"
version = "0.1.0"
authors = ["Jonas Lauschke"]
edition = "2021"
license = "AGPL-3.0"

[dependencies]
actix-web = { version = "4.0.1" }
bytecheck = "0.6.8"
bytes = "1.1.0"
env_logger = "0.9.0"
futures = "0.3.21"
log = "0.4.17"
rkyv = { version = "0.7.38", features = ["bytecheck", "validation", "rend", "archive_be"] }
sled = "0.34.7"
tokio = "1.18.2"
zerocopy = "0.6.1"
einkaufsliste = {path = "../" }

